### ISSUE TITLE
Update to garden 1.3.0

### ISSUE THREAD

**Issue by levitanong** [martinklepsch/boot-garden#11]

**Comment by martinklepsch** [comment]
:+1: PR most welcome!

**Comment by levitanong** [comment]
I'm a little hesitant, because I had to remove something to make it work. What I've done so far is remove the :refresh keyword from garden-pods. Keeping it in causes a java.io thread error, and removing it fixes the problem. Not sure if that breaks anything else.

**Comment by dgellow** [comment]
What's the status of this issue?

**Comment by martinklepsch** [comment]
@dgellow @levitanong there are [some changes](https://github.com/boot-clj/boot/compare/2.4.2...master) queued for the next release of boot that might remove the need for any specific workarounds as done in #14.

I'd like to verify the workarounds are still required with the coming release before adding them to the codebase. Does this sound ok to you?

**Comment by levitanong** [comment]
I remember someone mentioning an evergreen feature of boot on hipchat. Is this it?

Regardless, you’re right, we should wait for the coming release (and even then, garden 1.3.0 is still a snapshot) before doing anything.

**Comment by martinklepsch** [comment]
What evergreen feature of boot do you mean? I'm afraid I didn't understand
the first portion of your comment :)

I think the next boot release is around the corner so we shouldn't have to
wait very long :)

**Comment by dgellow** [comment]
@martinklepsch 
> I'd like to verify the workarounds are still required with the coming release before adding them to the codebase. Does this sound ok to you?

It sounds totally fine to me :)
I'll wait your release before moving my project to Garden `1.3.0`. 

Btw thank you for your work.

**Comment by levitanong** [comment]
@martinklepsch iirc, someone somewhere mentioned something about boot decoupling dependency versions, and keeping all the things up to date. But I could've been high at the time.

https://github.com/noprompt/garden
Garden is now stable at 1.3.0!

**Comment by martinklepsch** [comment]
@levitanong Hey! I just pushed a new version `1.3.0-0` that should come with Garden 1.3.0 — give it a try :+1:

**Comment by levitanong** [comment]
@martinklepsch works perfectly. Thanks man!

**Comment by martinklepsch** [comment]
Cool, thanks for letting me know! :)
