### ISSUE TITLE
Use boot-garden to compile styles in CLJS files

### ISSUE THREAD

**Issue by crimeminister** [martinklepsch/boot-garden#21]
I have a project in which I am using perun to generate a static front-end sales site and Om.Next for the application functionality. Using boot-garden with perun works great (thanks!); would it be possible to extend it to process styles stored in CLJS files as well?

**Comment by mebster** [comment]
+1. Similarly, we have a re-frame web app all in Clojurescript.  So having styling done in .cljs files alongside their component is more elegant.

**Comment by martinklepsch** [comment]
Hey! And sorry for the late response @crimeminister & @mebster :)

Currently boot-garden produces a file which can then be loaded using a classing `<link>` tag. With a CLJS based approach would you still want to produce a file? 

How can the task know what rules to include? I haven't used Garden in CLJS so any explanation of how you use it (and maybe some example code) would be helpful.

**Comment by crimeminister** [comment]
Closing as this issue is rather long in the tooth!
