### ISSUE TITLE
Pretty print option is not working

### ISSUE THREAD

**Issue by tungd** [martinklepsch/boot-garden#6]
I tried the following snippet and the output stylesheet is still pretty-printed:

    (set-env!
     :source-paths #{"src/clj" "src/cljs"}
     :target-path "public"
     :dependencies '[[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "0.0-3308"]
                 [reagent "0.5.0"]
                 [garden "1.2.5"]
                 ;; Boot dependencies
                 [adzerk/boot-cljs "0.0-3269-2" :scope "test"]
                 [adzerk/boot-cljs-repl "0.1.9" :scope "test"]
                 [adzerk/boot-reload "0.2.6" :scope "test"]
                 [org.martinklepsch/boot-garden "1.2.5-5" :scope "test"]])

    (deftask build-garden []
      (garden :styles-var 'new-project.styles/screen
              :output-to "css/screen.min.css"
              :pretty-print false))

I then tried:

    boot garden -p false -s new-project.styles/screen

and get `NullPointerException`. Please help.

**Comment by martinklepsch** [comment]
Hey @tungd — thanks for reporting this. I was missing a `?` when passing the pretty print option to the garden compiler. Please try  `1.2.5-6` and let me know if that fixes it :+1: 

https://github.com/martinklepsch/boot-garden/commit/13e44a1a7d6ec5655fbdc74a2037ee578d09d640

**Comment by tungd** [comment]
It works now. Thank you very much!
