### ISSUE TITLE
Exception when defining two or more garden tasks

### ISSUE THREAD

**Issue by tungd** [martinklepsch/boot-garden#9]
Hi, I'm trying to get two garden tasks for backend and frontend, the task definition is:

```clojure
(deftask dev []
  (comp
    (garden :styles-var 'site.frontend.style/screen
          :output-to "css/frontend.css"
          :pretty-print false)
    (garden :styles-var 'site.backend.style/screen
          :output-to "css/backend.css"
          :pretty-print false)))
```

I got the following exception: http://pastebin.com/wnXaspGX.

Please help. Thank you.

**Comment by martinklepsch** [comment]
Are you using `[org.martinklepsch/boot-garden "1.2.5-7"]` ? 

This problem should only occur with version prior to that.

See #7, #8 & https://github.com/boot-clj/boot/issues/270 for details.

**Comment by tungd** [comment]
My bad, I'm using Garden 1.2.5-6 and did not catch up with the development. Thank you so much for the good work.

**Comment by martinklepsch** [comment]
No problem :+1:
